### PR TITLE
Issue #20: Integrate firebase crashlytics

### PR DESCRIPTION
**Pull request by SalosV**
**Implementation of crashlytics:** #20 
- Crashlyticis functionality added

**Testing Done:**

* On Emulator: Huawei P20 Lite.

**How To Test:**

In the activity add these lines code

````
   val crashButton = Button(this)
   crashButton.text = "Crash!"
   crashButton.setOnClickListener {
      Crashlytics.getInstance().crash() // Force a crash
   }

    addContentView(crashButton, ViewGroup.LayoutParams(
    ViewGroup.LayoutParams.MATCH_PARENT,
    ViewGroup.LayoutParams.WRAP_CONTENT))
````

compile the application and press the button that appears on the screen, When you press the button the application will close. to look at the fault that has been generated you have to enter [Firebase](https://console.firebase.google.com/u/0/) and look for the MU8APP project, when you find the project look for the Crashlytics module and the error report will appear there.

Captura de Pantalla 2019-12-03 a la(s) 12 26 07 a  m

**Signed-off-by:**

`Santiago Lozada <santiagolozada95@gmail.com>`

### CODE REVIEW

**Comment by recaldev** [comment]
> **Implementation of crashlytics:** #20
> 
> * Crashlyticis functionality added
> 
> Captura de Pantalla 2019-12-03 a la(s) 12 26 07 a  m
> 
> **Testing Done:**
> 
> * On Emulator: Huawei P20 Lite.
> 
> **How To Test:**
> 
> In the activity add these lines code
> 
> ```
>    val crashButton = Button(this)
>    crashButton.text = "Crash!"
>    crashButton.setOnClickListener {
>       Crashlytics.getInstance().crash() // Force a crash
>    }
> 
>     addContentView(crashButton, ViewGroup.LayoutParams(
>     ViewGroup.LayoutParams.MATCH_PARENT,
>     ViewGroup.LayoutParams.WRAP_CONTENT))
> ```
> 
> **Signed-off-by:**
> 
> `Santiago Lozada <santiagolozada95@gmail.com>`

@SalosV the how to test section seems incomplete, you're saying what to add to make the app crash which is good, but you're not telling us the next step which is going to the firebase console, go to the crashlytics section and check for the crash to appear. Think as this was going to be reviewed by a Junior Dev that doesn't even know what firebase and craslytics are and provide as much detail as possible.

**Review by recaldev — CHANGES_REQUESTED** [review]
@SalosV your branch doesn't compile, did you push the google-services.json?

image

**Comment by recaldev** [comment]
> **Implementation of crashlytics:** #20
> 
> * Crashlyticis functionality added
> 
> **Testing Done:**
> 
> * On Emulator: Huawei P20 Lite.
> 
> **How To Test:**
> 
> In the activity add these lines code
> 
> ```
>    val crashButton = Button(this)
>    crashButton.text = "Crash!"
>    crashButton.setOnClickListener {
>       Crashlytics.getInstance().crash() // Force a crash
>    }
> 
>     addContentView(crashButton, ViewGroup.LayoutParams(
>     ViewGroup.LayoutParams.MATCH_PARENT,
>     ViewGroup.LayoutParams.WRAP_CONTENT))
> ```
> 
> compile the application and press the button that appears on the screen, When you press the button the application will close. to look at the fault that has been generated you have to enter [Firebase](https://console.firebase.google.com/u/0/) and look for the MU8APP project, when you find the project look for the Crashlytics module and the error report will appear there.
> 
> Captura de Pantalla 2019-12-03 a la(s) 12 26 07 a  m
> 
> **Signed-off-by:**
> 
> `Santiago Lozada <santiagolozada95@gmail.com>`

@SalosV please update the title of you PR as we have been doing with the others: `Issue #Your Issue: Your Issue Description`

**Review by jamacado — APPROVED** [review]

**Review by jamacado — APPROVED** [review]
imagen

**Review by aliceresponde — APPROVED** [review]
LG

**Pull request merged**
